### ISSUE TITLE
can't build it: linker command failed 

### ISSUE THREAD

**Issue by macchrissli** [KhaosT/HomeKitBridge#12]
"_OBJC_CLASS_$_HAKIdentifyCharacteristic", referenced from:
      objc-class-ref in OTIContentController.o
      objc-class-ref in HueLight.o
  "_OBJC_CLASS_$_HAKOnCharacteristic", referenced from:
      objc-class-ref in HueLight.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Jedih** [comment]
I about to try this - when you say "You'll need to use a HomeKit app to setup the light (aka Pair with the light)", does that mean e.g. the Philips Hue app on my iPhone? Or do I need to download another app on my iPhone to get it to work with Siri?

**Comment by KhaosT** [comment]
@Jedih I mean an app that supports HomeKit. Currently I don't think there is anything available on App Store yet. You can try [this one](https://github.com/KhaosT/HomeKit-Demo).
