### ISSUE TITLE
[Question] - Home and Philips hue

### ISSUE THREAD

**Issue by taovo** [KhaosT/HomeKitBridge#13]
Hi guy,

Could you please help me answer my question?

"Homekit work with Philips hue as well? I mean we do not use the HUE SDK, only homekit and philips HUE". I'm in vietnam, and i want to implement homekit with real devices, the philips HUE is very expensive in Vietname, that's why i want to comfirm with you about it." 

Thank you

**Comment by KhaosT** [comment]
@taovo Currently Philips Hue doesn't support HomeKit. Although Philips says they will support HomeKit for Hue in the future, it seems they are having issues due to the conflict between Apple's MFi license and their way of implementing the Hue. Maybe in the future they will eventually support HomeKit, but for near future, it's not.

**Comment by taovo** [comment]
Thank you KhaosT, your information is very useful for me, I'm hoping it's
even possible for Philips to update the firmware on existing bridges so
that it'll work with HomeKit. As a developer of an app that works with
multiple hardware vendors, the prospect of using HomeKit instead of messing
with individual Philips, LIFX, WeMo, and ilumi SDKs sounds wonderful.

On Mon, Mar 9, 2015 at 3:06 PM, Khaos Tian <notifications@github.com> wrote:

> @taovo <https://github.com/taovo> Currently Philips Hue doesn't support
> HomeKit. Although Philips says they will support HomeKit for Hue in the
> future, it seems they are having issues due to the conflict between Apple's
> MFi license and their way of implementing the Hue. Maybe in the future they
> will eventually support HomeKit, but for near future, it's not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KhaosT/HomeKitBridge/issues/13#issuecomment-77813496>.
>



-- 
Regards,
*Tao Vo*
*Email: raintvh88@gmail.com <raintvh88@gmail.com> | Phone: +84 909 65 61 65*
*Web: http://taovh.com <http://taovh.com>*
*Skype: rain_tvh*
