### ISSUE TITLE
Can't see bridge when running on separate machines

### ISSUE THREAD

**Issue by deeka** [KhaosT/HomeKitBridge#15]
Hi,

First of all, thank you for sharing the bridge code with us.
I am having an issue with maybe has to do with my lack of understanding of how HomeKit works. I was able to create a bridge to control my devices (mainly lights for now.) When I run the bridge and the HomeKitDemo in the simulator everything works. The HomeKitDemo app can see the bridge, I can add the accessories and control my devices.
However, if I run the bridge on one machine and HomeKitDemo in the simulator on another machine, HomeKitDemo does not see the bridge when I try to add it as an accessory.

Is that an issue of entitlements or permissions across the network? Any pointers as to what could be the problem?

Many thanks.

**Comment by KhaosT** [comment]
@deeka Please make sure your network supports Bonjour discovery. Normally this happens because the second computer can't discover the HAP service on the first computer.

**Comment by deeka** [comment]
@KhaosT thanks for the quick reply. Is Bonjour discovery enabled at the wireless router level, machine level or app? I am running an airport extreme, Mac mini and powerbook.

**Comment by KhaosT** [comment]
@deeka Normally there isn't extra settings you need configure to support Bonjour for home network. You can try [Bonjour Browser](http://www.tildesoft.com/) and see if you can find HAP service. If you can't find the service on the other machine, you may want to try reboot the device, reboot router and maybe this will solve the problem.

**Comment by deeka** [comment]
@KhaosT almost there. Turns out I couldn't see the hap service as I was using vpn to connect to the host machine, which does not broadcast bonjour messages. I can now see the accessories using the iphone simulator on separate machines. However, if I try to to run a client on an ipad, i still don't see any accessories. Not sure what's going on.

**Comment by KhaosT** [comment]
@deeka If you can see the accessory in Simulator but not iPad, please check if iPad is connected to the same network...

**Comment by deeka** [comment]
@KhaosT I am on the same wifi network

**Comment by KhaosT** [comment]
@deeka Maybe try running iNet on your iPad and see if Bonjour Discovery works correctly for you?

**Comment by deeka** [comment]
@KhaosT thanks, i got it working.
