### ISSUE TITLE
Adding Thermostat Accessories

### ISSUE THREAD

**Issue by deeka** [KhaosT/HomeKitBridge#16]
Hi @KhaosT 
I hope I am not taking too much advantage of your knowledge. But I've hit a brick wall, and I am not sure how to proceed.
Here is my problem: I was able to create and add Thermostat accessories to my home kit bridge. The thermostats appear on the client side and I can add them to a home.
However, on the server side the "value" fields of the characteristics (TargetHeatCoolCharacteristic for example) is Nill on the server side, so I can not initialize it to any value.
I am not sure what is going on. In the debugger, the accessory has the right services, and if I look at the characteristis on the Thermostat service, it shows the correct constraints for each. It is just that the value field is Nill and can't be step.

Any ideas what's going on?

**Comment by KhaosT** [comment]
@deeka I tried with a regular HMCharacteristic and all the value field looks correct for me. Are you sure you initialize the HMCharacteristic properly?
![screen shot 2015-04-13 at 2 42 08 pm](https://cloud.githubusercontent.com/assets/1725664/7126106/65ba6af8-e1eb-11e4-8a79-b394b2e8a4dd.png)

**Comment by deeka** [comment]
@KhaosT here is what i get in the debugger:
![screen shot 2015-04-13 at 8 38 22 pm](https://cloud.githubusercontent.com/assets/2332155/7128233/51c64300-e21d-11e4-9e20-f4f1c518e134.png)

**Comment by deeka** [comment]
@KhaosT notice how _value is 0x0

**Comment by KhaosT** [comment]
@deeka does this happen to all characteristics or only specific ones?

**Comment by KhaosT** [comment]
@deeka works for me 
![screen shot 2015-04-13 at 5 51 03 pm](https://cloud.githubusercontent.com/assets/1725664/7128344/b718e9c8-e205-11e4-8db2-7545015f278a.png)

**Comment by deeka** [comment]
@KhaosT creating a characteristic directly works. Try creating a thermostat accessory, and traverse down to the service to the characteristic. Do you see a valid value field?

**Comment by KhaosT** [comment]
@deeka would you mind to post the code to setup the "thermostat accessory" or provide a sample project so I can test?

**Comment by deeka** [comment]
@KhaosT  here is the code:
![screen shot 2015-04-13 at 9 10 16 pm](https://cloud.githubusercontent.com/assets/2332155/7128542/c1921c3c-e221-11e4-8135-48bf75703f30.png)

**Comment by KhaosT** [comment]
@deeka I have no problem associating value to characteristics.
![screen shot 2015-04-13 at 7 08 50 pm](https://cloud.githubusercontent.com/assets/1725664/7129097/9b25fa70-e210-11e4-92a2-f1eb1b9227ac.png)

**Comment by deeka** [comment]
@KhaosT do me a favor, can you try setting the TemperatureUnits characteristics to Fahrenheit, then set both the target and current temperature to 55. That doesn't work for me. CurrentTemperature gets set, but TargetTemperature is nil.

**Comment by KhaosT** [comment]
@deeka the entire HAPAccessoryKit operates on Celsius even if you set the unit to fahrenheit. Setting a target temperature to 55 exceeded the max limit (38) so you will not be able to success.

**Comment by deeka** [comment]
@KhaosT you're correct. Thanks for your help
