### ISSUE TITLE
Internal Service Error when running on iPhone device

### ISSUE THREAD

**Issue by deeka** [KhaosT/HomeKitBridge#17]
@KhaosT have you come across this error before? My client runs fine in the simulator, but when i try to run the client on an iphone6 device, I get the following error:

2015-04-16 18:45:03.248 HomeControl[6766:2329562] found accessory Lutron Bridge 1.0
2015-04-16 18:45:07.792 HomeControl[6766:2329562] failed to add accessory Lutron Bridge 1.0 to home: Error Domain=HMErrorDomain Code=59 "Failed with OSStatus code 200500 (Internal Server Error)" UserInfo=0x15e7f610 {NSLocalizedDescription=Failed with OSStatus code 200500 (Internal Server Error)}

**Comment by deeka** [comment]
error 59 in HMError.h is HMErrorCodeAccessoryResponseError, but I am not sure what that means

**Comment by KhaosT** [comment]
Accessory can only be paired with a single iOS device. After that, accessory will reject all new pair setup request.

**Comment by deeka** [comment]
really? so only one user can communicate with a thermostat for example?
that doesn't seem right

**Comment by KhaosT** [comment]
HomeKit's security model is for a house, there will only have a single admin creating the primary HMHome and pair all the accessories. All the family members will be able to control the accessories by asking admin to share the HMHome to them.

**Comment by deeka** [comment]
ah ok. makes sense. But how does the admin share an HMHone with other users?

**Comment by KhaosT** [comment]
@deeka See [Managing Users](https://developer.apple.com/library/ios/documentation/HomeKit/Reference/HMHome_Class/index.html#//apple_ref/doc/uid/TP40014466-CH1-DontLinkElementID_10)
