### ISSUE TITLE
JB AppleTV Possible?

### ISSUE THREAD

**Issue by infused-kim** [KhaosT/HomeKitBridge#18]
Hi,

Would it be at all possible to make this work on non-macs? I am specifically thinking of compiling this for a jailbroken Apple TV to make it permanent in my home.

Greetings, Kim

**Comment by KhaosT** [comment]
Sorry, since this project uses Apple's Library HAKAccessoryKit, it's not possible to port to other platforms. You may want to check [this](https://github.com/KhaosT/HAP-NodeJS), which can be host on Raspberry Pi.
